name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'  # Only runs on version tags like v1.0.0

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile --noconsole main.py

    - name: Upload EXE to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/main.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
